### ISSUE TITLE
Simplify Browser Usage

### ISSUE THREAD

**Issue by ritch** [strongloop/strong-pubsub#18]
Right now you have to jump through a couple hoops to get strong-pubsub work in the browser.

**Tasks**
- [ ] Improve the browser example
- [ ] Fix strong-pubsub-primus so it can be used in the browser
- [ ] Create a section in the strong-pubsub readme that clarifies how to use in the browser

/cc @superkhau @crandmck

**Comment by superkhau** [comment]
@0candy Reassigning to you since you are the expert, feel free to prioritize it accordingly.

**Comment by dhmlau** [comment]
Closing due to inactivity.
